# Generated by Django 5.2.1 on 2025-05-25 06:07

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('empresa', 'Empresa'), ('persona', 'Persona')], default='empresa', max_length=10)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('tasa', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasa_congelada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_minimo_congelado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tramo_cobro', models.PositiveIntegerField()),
                ('tipo_alcance', models.CharField(choices=[('minorista', 'Minorista')], default='minorista', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_transporte', models.CharField(choices=[('Aereo', 'Aéreo'), ('Maritimo', 'Marítimo'), ('TerrestreFerroviario', 'Terrestre y/o Ferroviario'), ('MarRojo', 'Marítimo vía Mar Rojo')], max_length=50)),
                ('tipo_carga', models.CharField(choices=[('PolizaGeneral', 'Póliza para Carga General y/o Carga Seca'), ('PolizaCongelada', 'Póliza para Carga Congelada')], max_length=50)),
                ('clausula', models.CharField(choices=[('A', 'Tipo A'), ('C', 'Tipo C')], max_length=10)),
                ('tipo_embalaje_aereo', models.CharField(blank=True, max_length=100, null=True)),
                ('otro_embalaje_aereo', models.CharField(blank=True, max_length=100, null=True)),
                ('embalaje_maritimo', models.CharField(blank=True, choices=[('FCL', 'FCL'), ('LCL', 'LCL')], max_length=10, null=True)),
                ('tipo_container_maritimo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_embalaje_lcl', models.CharField(blank=True, max_length=100, null=True)),
                ('otro_embalaje_lcl', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_embalaje_terrestre', models.CharField(blank=True, max_length=100, null=True)),
                ('otro_embalaje_terrestre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotasNumeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('guia_carga', models.CharField(max_length=100)),
                ('numero_factura', models.CharField(max_length=100)),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_origen', models.CharField(max_length=100)),
                ('ciudad_origen', models.CharField(max_length=100)),
                ('pais_destino', models.CharField(max_length=100)),
                ('ciudad_destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Maquinaria', 'Maquinaria y aparatos mecánicos, equipos electrónicos en FCL o LCL'), ('General', 'Mercancía General'), ('Aeronaves', 'Piezas de Aeronaves'), ('Hierro', 'Productos de hierro y acero')], max_length=30)),
                ('valor_fca', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_flete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_asegurado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_prima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_avion', models.CharField(max_length=100)),
                ('numero_viaje', models.CharField(max_length=100)),
                ('vuelo_origen_pais', models.CharField(max_length=100)),
                ('vuelo_origen_ciudad', models.CharField(max_length=100)),
                ('aeropuerto_origen', models.CharField(max_length=100)),
                ('vuelo_destino_pais', models.CharField(max_length=100)),
                ('vuelo_destino_ciudad', models.CharField(max_length=100)),
                ('aeropuerto_destino', models.CharField(max_length=100)),
                ('descripcion_carga', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.CharField(default='01930324AA', max_length=20)),
                ('compania', models.CharField(default='SafeYourCargo', max_length=50)),
                ('fecha_partida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('metodo_embarque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.metodoembarque')),
                ('notas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.notasnumeros')),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
                ('tipo_mercancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tipomercancia')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pendiente_aprobacion', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Revendedor', 'Revendedor')], default='Usuario', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.cliente')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('valor_fca', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_flete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_asegurado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prima_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prima_cobro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prima_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza', to='core.certificadotransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('valor_usd', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=Decimal('950.0'), max_digits=10)),
                ('valor_clp', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.certificadotransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='core.pais')),
            ],
        ),
    ]
