# Generated by Django 5.2.1 on 2025-06-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='vuelo_destino_pais_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destino', to='core.pais'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='vuelo_origen_pais_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_origen', to='core.pais'),
        ),
    ]
