# Generated by Django 5.2.1 on 2025-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_viaje_vuelo_destino_pais_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='sigla',
            field=models.CharField(default='x', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
