# Generated by Django 5.2.1 on 2025-06-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pais_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='folio_sii',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
