# Generated by Django 5.2.1 on 2025-06-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cliente_correo_remove_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_alcance',
        ),
    ]
