# Generated by Django 5.2.1 on 2025-06-11 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cliente_tipo_alcance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificadotransporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Certificado de Transporte', 'verbose_name_plural': 'Certificados de Transporte'},
        ),
        migrations.AddField(
            model_name='certificadotransporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='certificadotransporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificadotransporte',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='notasnumeros',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notasnumeros',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notasnumeros',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
