# Generated by Django 5.2.1 on 2025-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_factura_estado_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_emision',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('exito', 'Emitida exitosamente'), ('fallida', 'Con error'), ('duplicado', 'Folio ya usado')], max_length=20, null=True),
        ),
    ]
