# Generated by Django 5.2.1 on 2025-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_factura_estado_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.PositiveSmallIntegerField()),
                ('desde', models.PositiveIntegerField()),
                ('hasta', models.PositiveIntegerField()),
                ('fecha_autorizacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
