# Generated by Django 5.2.1 on 2025-07-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_caf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_minimo_congelado',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
