# Generated by Django 5.2.1 on 2025-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cliente_valor_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadotransporte',
            name='valor_prima_cobro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='certificadotransporte',
            name='valor_prima_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='certificadotransporte',
            name='valor_prima_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
