# Generated by Django 5.2.1 on 2025-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificadotransporte_valor_prima_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tasa_congelada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
