# Generated by Django 5.2.1 on 2025-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cliente_tasa_alter_cliente_tasa_congelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tasa',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_minimo_congelado',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
