# Generated by Django 5.2.1 on 2025-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cliente_tasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='url_pdf_sii',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL PDF SII'),
        ),
    ]
