# Generated by Django 5.2.1 on 2025-07-27 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_factura_url_pdf_sii'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico adicional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Adicional',
                'verbose_name_plural': 'Emails Adicionales',
                'unique_together': {('usuario', 'email')},
            },
        ),
    ]
