# Generated by Django 5.2.1 on 2025-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_emailadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_iata', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('codigo_icao', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
            },
        ),
    ]
