# Generated by Django 5.2.1 on 2025-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aerolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='codigo_icao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
