# Generated by Django 5.2.1 on 2025-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aerolinea_codigo_icao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('imo', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('mmsi', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('bandera', models.CharField(blank=True, max_length=100, null=True)),
                ('naviera', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Navío',
                'verbose_name_plural': 'Navíos',
                'ordering': ['nombre'],
            },
        ),
    ]
