# Generated by Django 5.2.1 on 2025-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_navio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoembarque',
            name='tipo_container_maritimo',
            field=models.CharField(blank=True, choices=[('DRY', 'DRY'), ('REEFER', 'REEFER'), ('HIGH CUBE', 'HIGH CUBE'), ('OPEN TOP', 'OPEN TOP'), ('FLAT RACK', 'FLAT RACK'), ('FLEX TANK', 'FLEX TANK'), ('ISO TANK', 'ISO TANK'), ('FLEXI TANK', 'FLEXI TANK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metodoembarque',
            name='tipo_embalaje_aereo',
            field=models.CharField(blank=True, choices=[('CAJAS_CARTON', 'Cajas de cartón'), ('CAJAS_MADERA', 'Cajas de madera'), ('CAJAS_PLASTICO', 'Cajas de plástico'), ('PALLETS', 'Pallets'), ('OTRO', 'OTRO: Especificar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metodoembarque',
            name='tipo_embalaje_lcl',
            field=models.CharField(blank=True, choices=[('CAJAS_CARTON', 'Cajas de cartón'), ('CAJAS_MADERA', 'Cajas de madera'), ('CAJAS_PLASTICO', 'Cajas de plástico'), ('PALLETS', 'Pallets'), ('OTRO', 'OTRO: Especificar')], max_length=100, null=True),
        ),
    ]
