# Generated by Django 5.2.1 on 2025-08-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_metodoembarque_tipo_container_maritimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=15),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['creado_por', 'rut'], name='core_client_creado__29d817_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['creado_por', 'nombre'], name='core_client_creado__916a00_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('creado_por', 'rut'), name='uniq_owner_rut'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('creado_por', 'nombre'), name='uniq_owner_nombre'),
        ),
    ]
