# Generated by Django 5.2.1 on 2025-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_cliente_nombre_alter_cliente_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlocodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('locode', models.CharField(db_index=True, max_length=5)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('function', models.CharField(blank=True, max_length=10, null=True)),
                ('subdiv', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=3, null=True)),
                ('iata', models.CharField(blank=True, max_length=3, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'function'], name='core_unloco_country_a45f73_idx'), models.Index(fields=['locode'], name='core_unloco_locode_fde350_idx'), models.Index(fields=['name'], name='core_unloco_name_865b55_idx')],
                'unique_together': {('country_code', 'locode')},
            },
        ),
    ]
