# Generated by Django 5.2.1 on 2025-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_unlocodeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='emitir_factura_automatica',
            field=models.BooleanField(default=True, help_text='Desactiva esta opción si el cliente maneja su propia facturación.', verbose_name='Emitir factura automáticamente'),
        ),
    ]
