# Generated by Django 5.2.1 on 2025-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_usuario_emitir_factura_automatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoembarque',
            name='tipo_embalaje_terrestre',
            field=models.CharField(blank=True, choices=[('FLC', 'FLC (En camión)'), ('LCL', 'LCL (En camión)'), ('OTRO', 'Otro (especificar)')], max_length=100, null=True),
        ),
    ]
