# Generated by Django 5.2.1 on 2025-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_metodoembarque_tipo_embalaje_terrestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='aeropuerto_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='aeropuerto_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
